#!/bin/sh

get_ip() {
    if [ "$(uname -s)" = "Darwin" ]; then
        ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'
    elif [ "$(uname -s)" = "Linux" ]; then
        hostname -I | awk '{print $1}'
    fi
    curl -s https://api.ipify.org
    echo -e "\n"


    if [ "$(uname -s)" = "Darwin" ]; then
        ifconfig | grep 'inet6 ' | grep -v 'fe80' | awk '{print $2}' | head -n 1
    elif [ "$(uname -s)" = "Linux" ]; then
        hostname -I | awk '{print $1}' | grep -Eo '([0-9a-fA-F:]+)' | head -n 1
    fi

    curl -s https://api6.ipify.org
    echo -e "\n"
}

