#!c/bin/sh
#POSIX-compliant for sourcing from sh, bash, zsh

desk() {
    file="${HOME}/desktop"
    cd "$file"
}

dot() {
    file="${HOME}/dotfilesx"
    cd "$file"
}

down() {
    file="${HOME}/downloads"
    cd "$file"
}

hack() {
    file="${HOME}/hack"
    cd "$file"
}

pragma() {
    file="${HOME}/pragma"
    cd "$file"
}

srs() {
    file="${HOME}/srs"
    cd "$file"
}

app_support() {
    file="${HOME}/Library/Application\ Support"
    cd "$file"
}

unset file

alias rm='rm -i'

l() {
    ls --color
}

ll() {
    ls -AlF
}

lx() {
    #@ shows extended attributes [metatdata beyond file attrs] (xattr -l)
    ls -Al@ --color
}

le() {
    #e shows ACLs (Access Control Lists) [extra file permissions] (macos-specific)
    ls -AlFe --color
}

lxe() {
    ls -Al@e --color
}

lex() {
    ls -Al@e --color
}

ld() {
    ls -dl --color */
}

rl() {
    shell="$(ps -p $$ -o comm=)"
    case "$shell" in
    *zsh*)
        . "${HOME}/.zshrc"
        ;;
    *bash*)
        . "${HOME}/.bashrc"
        ;;
    *sh*)
        . "${HOME}/.shrc"
        ;;
    *)
        echo "Unsupported shell: $shell"
        ;;
    esac
    echo "Reloaded $shell"
    unset shell
}


