#!c/bin/sh
#POSIX-compliant for sourcing from sh, bash, zsh

desk() {
    file="${HOME}/desktop"
    cd "$file"
}

dot() {
    file="${HOME}/dotfilesx"
    cd "$file"
}

down() {
    file="${HOME}/downloads"
    cd "$file"
}

hack() {
    file="${HOME}/hack"
    cd "$file"
}

play() {
    file="${HOME}/play"
    if [[ ! -d "$file" ]]; then
        mkdir -p "$file"
    fi
    cd "$file"
}

pragma() {
    file="${HOME}/pragma"
    cd "$file"
}

srs() {
    file="${HOME}/srs"
    cd "$file"
}

app_support() {
    file="${HOME}/Library/Application\ Support"
    cd "$file"
}

unset file

alias rm='rm -i'
alias ls='ls --color'

l() {
    ls "$@"
}

ll() {
    ls -AlF "$@"
}

lx() {
    #@ shows extended attributes [metatdata beyond file attrs] (xattr -l)
    ls -Al@ "$@"
}

le() {
    #e shows ACLs (Access Control Lists) [extra file permissions] (macos-specific)
    ls -AlFe "$@" 
}

lxe() {
    ls -Al@e "$@"
}

lex() {
    ls -Al@e "$@"
}

ld() {
    ls -dl "$@" */
}

rl() {
    shell="$(ps -p $$ -o comm=)"
    case "$shell" in
    *zsh*)
        . "${HOME}/.zshrc"
        ;;
    *bash*)
        . "${HOME}/.bashrc"
        ;;
    *sh*)
        . "${HOME}/.shrc"
        ;;
    *)
        echo "Unsupported shell: $shell"
        ;;
    esac
    echo "Reloaded $shell"
    unset shell
}


