#!/usr/bin/env zsh
#----------------------------------------------------------------------------------------------
#
umask 077
#----------------------------------------------------------------------------------------------
setopt extendedglob
setopt dotglob

# Platform detection
if [[ "$OSTYPE" == "darwin"* ]]; then
    IS_MACOS=true
    if [[ $(uname -m) == "arm64" ]]; then
        IS_M1=true
    fi
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    IS_LINUX=true
fi

# Optimized load_fn using zsh globbing
load_fn() {
    local dir="${HOME}/dotfilesx/fn"
    fpath+=("$dir" "$dir"/**/*(N/))
    for file in "$dir"/*(N); do
        local func_name="${file:t:r}"
        autoload -Uz "$func_name"
    done
}
load_fn
#----------------------------------------------------------------------------------------------
export DOTFILES="${HOME}/dotfilesx"
export ZSH_DOTFILES="${DOTFILES}/zsh"

#NOTE: xdg
export XDG_CONFIG_HOME="${DOTFILES}"

export STARSHIP_CONFIG=~/dotfilesx/starship/starship.toml
#----------------------------------------------------------------------------------------------
#NOTE: homebrew
if [[ "$IS_MACOS" == true ]]; then
    if [[ "$IS_M1" == true ]]; then
        HOMEBREW_PREFIX="/opt/homebrew"
    else
        HOMEBREW_PREFIX="/usr/local"
    fi
    export HOMEBREW_PREFIX
    export HOMEBREW_CELLAR="$HOMEBREW_PREFIX/Cellar"
    export HOMEBREW_REPOSITORY="$HOMEBREW_PREFIX"
    export PATH="$HOMEBREW_PREFIX/bin:$HOMEBREW_PREFIX/sbin${PATH+:$PATH}"
    export MANPATH="$HOMEBREW_PREFIX/share/man${MANPATH+:$MANPATH}:"
    export INFOPATH="$HOMEBREW_PREFIX/share/info:${INFOPATH:-}"
    eval "$($HOMEBREW_PREFIX/bin/brew shellenv)"
elif [[ "$IS_LINUX" == true ]]; then
    HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew"
    export HOMEBREW_PREFIX
    export HOMEBREW_CELLAR="$HOMEBREW_PREFIX/Cellar"
    export HOMEBREW_REPOSITORY="$HOMEBREW_PREFIX"
    export PATH="$HOMEBREW_PREFIX/bin:$HOMEBREW_PREFIX/sbin${PATH+:$PATH}"
    export MANPATH="$HOMEBREW_PREFIX/share/man${MANPATH+:$MANPATH}:"
    export INFOPATH="$HOMEBREW_PREFIX/share/info:${INFOPATH:-}"
    eval "$($HOMEBREW_PREFIX/bin/brew shellenv)"
    export PATH="/usr/local/bin:${PATH}"
fi
#----------------------------------------------------------------------------------------------
#NOTE: editor
export TERM='screen-256color'
EDITOR="vi"
export EDITOR="nvim"

alias conf="cd ${DOTFILES} && $EDITOR ."
alias zconf="cd ${DOTFILES}/zsh && $EDITOR ."
alias vconf="cd ${DOTFILES}/nvim && $EDITOR ."
#----------------------------------------------------------------------------------------------
#NOTE: volta, node, pnpm
if [[ "$IS_MACOS" == true ]]; then
    export PNPM_HOME="${HOME}/Library/pnpm"
else
    export PNPM_HOME="${HOME}/.local/share/pnpm"
fi
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
#----------------------------------------------------------------------------------------------
#NOTE: rustup, rustc, cargo
# (No install logic here, just environment if needed)
#----------------------------------------------------------------------------------------------
ZINIT_HOME="${DOTFILES}/zinit/zinit"
source "${ZINIT_HOME}/zinit.zsh"

zmodload zsh/complist
autoload -Uz _zinit
fpath+="${ZSH_DOTFILES}/.zsh_functions"
fpath+="${ZSH_DOTFILES}/fn"
autoload -Uz $fpath/*(.N)
(( ${+_comps} )) && _comps[zinit]=_zinit

zinit ice wait
zinit light zsh-users/zsh-autosuggestions
zinit ice wait
zinit light zdharma-continuum/fast-syntax-highlighting
zinit ice wait
zinit light zsh-users/zsh-completions
zinit ice wait
zinit light MichaelAquilina/zsh-you-should-use
zinit ice wait
zinit light wfxr/forgit

# Zsh:
[ -f $HOMEBREW_PREFIX/share/forgit/forgit.plugin.zsh ] && source $HOMEBREW_PREFIX/share/forgit/forgit.plugin.zsh

zinit ice wait
zinit snippet OMZP::git
zinit ice wait
zinit snippet OMZP::sudo
#----------------------------------------------------------------------------------------------
ALACRITTY_HOME="${DOTFILES}/alacritty"
ALACRITTY_CONFIG_MACOS="${DOTFILES}/alacritty/alacritty-macos.toml"
ALACRITTY_CONFIG_LINUX="${DOTFILES}/alacritty/alacritty-linux.toml"

if [[ "$IS_MACOS" == true ]]; then
    ALACRITTY_CONFIG="${ALACRITTY_CONFIG_MACOS}"
else
    ALACRITTY_CONFIG="${ALACRITTY_CONFIG_LINUX}"
fi
export ALACRITTY_CONFIG
ALACRITTY_DESKTOP="${DOTFILES}/alacritty/Alacritty.desktop"
#----------------------------------------------------------------------------------------------
#case insensitive matching
zstyle ':completion:*' matcher-list 'm:{a-z}=m:{A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*': fzf-preview 'ls --color $realpath'

HISTSIZE=10000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

#ctrl+r, ctrl+p, ctrl+n,
eval "$(fzf --zsh)"
eval "$(zoxide init zsh)"
eval "$(starship init zsh)"

source "${DOTFILES}/aliases"

function fzf_file() {
    selected_file=$(fzf --preview '([[ -f {} ]] && (bat --style=numbers --colors=always {} || cat {})) ([[ -d {} ]] && (tree -C {} | less)) || echo {} 2>/dev/null | head -200')
    if [[ -n "$selected_file" && -e $selected_file ]]; then
        nvim -o "$selected_file"
    fi
}

bindkey '^/' history-search-backward
bindkey -s '^O' 'fzf_file\n'

#use for testing release candidates before deloying on production server
alias runpreprod='cd ~/srs/mindhuntr && pnpm prod:build && cd ~/srs/mindhuntr/build && ENV_PATH=~/srs/mindhuntr/etc/mindhuntr/.env node server.js'

#----------------------------------------------------------------------------------------------
if [[ "$IS_LINUX" == true ]]; then
    export LIBTORCH='/usr/share/libtorch'
    export LD_LIBRARY_PATH=$LIBTORCH:$LD_LIBRARY_PATH
fi

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
if [[ "$IS_MACOS" == true ]]; then
    __conda_setup="$('/Users/hq/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
    if [ $? -eq 0 ]; then
        eval "$__conda_setup"
    else
        if [ -f "/Users/hq/miniconda3/etc/profile.d/conda.sh" ]; then
            . "/Users/hq/miniconda3/etc/profile.d/conda.sh"
        else
            export PATH="/Users/hq/miniconda3/bin:$PATH"
        fi
    fi
    unset __conda_setup
fi
# <<< conda initialize <<<

