source /home/m/dotfilesx/bash/completions/alacritty
source /home/m/dotfilesx/bash/completions/alacritty
source /home/m/dotfilesx/bash/completions/alacritty
source /home/m/dotfilesx/bash/completions/alacritty
source /home/m/dotfilesx/bash/completions/alacritty
source /home/m/dotfilesx/bash/completions/alacritty
source /home/m/dotfilesx/bash/completions/alacritty
source /home/m/dotfilesx/bash/completions/alacritty
source /home/m/dotfilesx/bash/completions/alacritty
source /home/m/dotfilesx/bash/completions/alacritty
source /home/m/dotfilesx/bash/completions/alacritty
source /home/m/dotfilesx/bash/completions/alacritty
source /home/m/dotfilesx/bash/completions/alacritty
source /home/m/dotfilesx/bash/completions/alacritty
source /home/m/dotfilesx/bash/completions/alacritty
